<a href="https://colab.research.google.com/github/Matheusvfvitor/Py/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Importando numpy
import numpy as np  

In [2]:
np.__version__

'1.18.4'

In [3]:
#Criando Arrays
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [0]:
vector1 = np.array([0,1,2,3,4,5,6,7,8])

In [5]:
print(vector1)

[0 1 2 3 4 5 6 7 8]


In [6]:
vector1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [7]:
lst = [0,1,2,3,4,5,6,7,8]
type(lst)

list

In [0]:
vector2 = np.array(lst)

In [10]:
type(vector2)

numpy.ndarray

In [11]:
vector2[0]

0

In [0]:
vector2[0] = 100

In [13]:
print(vector2)

[100   1   2   3   4   5   6   7   8]


In [15]:
print(vector1.shape)

(9,)


Funções Numpy para criação de arrays

In [21]:
#np.arrange(Start, Stop, Step)
vector3 = np.arange(0.0,4.5,0.5) 
print(vector3)
print(type(vector3))
print(vector3.shape)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
<class 'numpy.ndarray'>
(9,)


In [22]:
vector4 = np.arange(0,10,2)
print(vector4)
print(type(vector4))
print(vector4.shape)

[0 2 4 6 8]
<class 'numpy.ndarray'>
(5,)


In [23]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
print(np.diag(np.array([1,2,3,4])))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [27]:
print(np.array([1+2j,3+4j,5+6j]))

[1.+2.j 3.+4.j 5.+6.j]


In [30]:
print(np.array([True, False, True, True]))
print(np.array(["Matheus", "Vinicius", "Felipe", "Vitor"]))

[ True False  True  True]
['Matheus' 'Vinicius' 'Felipe' 'Vitor']


In [33]:
print(np.linspace(0,10,15))
print(np.logspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]
[1.00000000e+00 5.17947468e+00 2.68269580e+01 1.38949549e+02
 7.19685673e+02 3.72759372e+03 1.93069773e+04 1.00000000e+05
 5.17947468e+05 2.68269580e+06 1.38949549e+07 7.19685673e+07
 3.72759372e+08 1.93069773e+09 1.00000000e+10]


Criando Matrizes com Numpy

In [0]:
matriz = np.array([[1,2,3],[4,5,6]])

In [35]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(matriz.shape)

(2, 3)


In [0]:
matriz1 = np.ones([2,3])

In [39]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
lista = [[13,81,22],[0,34,59],[21,48,94]]
matriz2 = np.matrix(lista)

In [41]:
type(matriz2)

numpy.matrix

In [44]:
np.shape(matriz2)

(3, 3)

In [45]:
matriz.size

6

In [46]:
matriz2.size

9

In [47]:
matriz2.dtype

dtype('int64')

In [48]:
matriz2.nbytes

72

In [49]:
print(matriz2[2,1])

48


In [0]:
matriz[1,0] = 100

In [51]:
matriz

array([[  1,   2,   3],
       [100,   5,   6]])

In [52]:
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2], dtype = np.float64)

print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [60]:
matriz4= np.matrix([[1,3],[2,1]], dtype = float)
print(matriz4)
print("Item size " + str(matriz4.itemsize))
print("Nbytes " + str(matriz4.nbytes))
print("Dimensões " + str(matriz4.ndim))

[[1. 3.]
 [2. 1.]]
Item size 8
Nbytes 32
Dimensões 2


In [0]:
A = np.array([15,23,18,94,121])

In [68]:
print("Média " + str(np.mean(A)))
print("Desvio Padrão " + str(np.std(A)))
print("variância " + str(np.var(A)))

Média 54.2
Desvio Padrão 44.422516812985734
variância 1973.36


In [73]:
d = np.arange(1,10)
print("Soma " + str(np.prod(d)))
print("Produto " + str(np.sum(d)))
print("CumSUM" + str(np.cumsum(d)))

Soma 362880
Produto 45
CumSUM[ 1  3  6 10 15 21 28 36 45]


In [77]:
a = np.random.randn(400,2)

-0.0006443676284336563


In [80]:
m = a.mean(0)
print(m, m.shape)

[ 0.07751699 -0.07880572] (2,)


Slicing de Arrays

In [0]:
a = np.diag(np.arange(3))

In [85]:
a[1,1]

1

In [86]:
a[1]

array([0, 1, 0])

In [89]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [88]:
b[2:9:3]

array([2, 5, 8])

In [90]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

a==b

array([False,  True, False,  True])

In [91]:
min(a)

1

In [92]:
max(a)

4

In [93]:
a+1.5

array([2.5, 3.5, 4.5, 5.5])

In [0]:
a = np.array([1.3,1.5,1.6,1.8,1.9,2.1])

In [0]:
b = np.around(a)

In [100]:
b

array([1., 2., 2., 2., 2., 2.])

In [0]:
B = np.array([1,2,3,4])
C = B.flatten()

In [103]:
print(C)

[1 2 3 4]


In [0]:
v = np.array([1,2,3])

In [107]:
v[:,np.newaxis],v[:,np.newaxis].shape, v[np.newaxis,:].shape

(array([[1],
        [2],
        [3]]), (3, 1), (1, 3))

In [108]:
np.repeat(v,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [109]:
np.tile(v,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [0]:
w = np.array([5,6])

In [111]:
np.concatenate((v,w), axis=0)

array([1, 2, 3, 5, 6])

In [0]:
r = np.copy(v)

In [113]:
print(r)

[1 2 3]
